export const paths = {
  index: '/',
  checkout: '/checkout',
  contact: '/contact',
  pricing: '/pricing',
  auth: {
    login: '/auth/login',
  },
  dashboard: {
    inicio: '/dashboard',
    proyectos: {
      index: '/dashboard/proyectos',
      crear: '/dashboard/proyectos/crear',
      presupuestos: '/dashboard/proyectos/presupuestos',
      fechas: '/dashboard/proyectos/fechas',
      pagos: '/dashboard/proyectos/pagos',
      ingresos: '/dashboard/proyectos/ingresos',
      asignaciones: '/dashboard/proyectos/asignaciones',
      revisiones: '/dashboard/proyectos/revisiones',
      inventario: '/dashboard/proyectos/inventario',
    },
    oficina: {
      personal: '/dashboard/oficina/personal',
      roles: '/dashboard/oficina/roles',
      ingresos: '/dashboard/oficina/ingresos',
      costos: '/dashboard/oficina/costos',
      materiales: '/dashboard/oficina/inventario/materiales',
      movimientos: '/dashboard/oficina/inventario/movimientos',
      pendientes: '/dashboard/oficina/pendientes',
    },
    maquinaria: {
      index: '/dashboard/maquinaria',
      asignaciones: '/dashboard/maquinaria/asignaciones',
      gastos: '/dashboard/maquinaria/gastos',
      estado: '/dashboard/maquinaria/estado',
    },
  },
  components: {
    index: '/components',
    dataDisplay: {
      detailLists: '/components/data-display/detail-lists',
      tables: '/components/data-display/tables',
      quickStats: '/components/data-display/quick-stats',
    },
    lists: {
      groupedLists: '/components/lists/grouped-lists',
      gridLists: '/components/lists/grid-lists',
    },
    forms: '/components/forms',
    modals: '/components/modals',
    charts: '/components/charts',
    buttons: '/components/buttons',
    typography: '/components/typography',
    colors: '/components/colors',
    inputs: '/components/inputs',
  },
  docs: 'https://material-kit-pro-react-docs.devias.io',
  notAuthorized: '/401',
  notFound: '/404',
  serverError: '/500',
};
