import { id } from "date-fns/locale";

export const paths = {
  index: '/',
  checkout: '/checkout',
  contact: '/contact',
  pricing: '/pricing',
  auth: {
    login: '/auth/login',
  },
  dashboard: {
    inicio: '/dashboard',  
    oficina: {
      socios: '/oficina/socios',
      planilla: '/oficina/planilla',
      roles: '/oficina/roles',
      ingresos: '/oficina/ingresos',
      costos: '/oficina/costos',
      inventario: '/oficina/inventario',
      ordenesCompra: '/oficina/ordenes-compra',
      rebajas: '/oficina/rebajas',
      traslados: '/oficina/traslados',
      materiales: '/oficina/materiales',
      unidades: '/oficina/unidades',
      marcas: '/oficina/marcas',
      proveedores: '/oficina/proveedores',
      crear: '/oficina/inventario/crear',
      rebajar: '/oficina/inventario/rebajar',
      trasladar: '/oficina/inventario/trasladar',
      orden_de_compra: (id: number) => `/oficina/ordenes-compra/${id}`,
      rebaja: (id: number) => `/oficina/rebajas/${id}`,
      movimiento_inventario: (id: number) => `/oficina/traslados-inventario/${id}`,
      movimientos_material: (id: number) => `/oficina/traslados-material/${id}`,
    },
    proyectos: {
      index: '/proyectos',
      crear: '/proyectos/crear',
      detalle: (id: number) => `/proyectos/${id}`,
      trasladar: (id: number) => `/proyectos/${id}/material-planificado/trasladar`,
      movimientos: (id: number, materialId: number) => `/proyectos/${id}/traslados-material/${materialId}`,
      configuracion: {
        tipoIngresos: '/proyectos/configuracion/tipo-ingresos',
        tipoPagos: '/proyectos/configuracion/tipo-pagos',
      }
    },
    maquinaria: {
      index: '/maquinaria',
      crear: '/maquinaria/crear',
      detalle: (id: number) => `/maquinaria/${id}`,
    },
  },
  components: {
    index: '/components',
    dataDisplay: {
      detailLists: '/components/data-display/detail-lists',
      tables: '/components/data-display/tables',
      quickStats: '/components/data-display/quick-stats',
    },
    lists: {
      groupedLists: '/components/lists/grouped-lists',
      gridLists: '/components/lists/grid-lists',
    },
    forms: '/components/forms',
    modals: '/components/modals',
    charts: '/components/charts',
    buttons: '/components/buttons',
    typography: '/components/typography',
    colors: '/components/colors',
    inputs: '/components/inputs',
  },
  docs: 'https://material-kit-pro-react-docs.devias.io',
  notAuthorized: '/401',
  notFound: '/404',
  serverError: '/500',
};
