export const paths = {
  index: '/',
  checkout: '/checkout',
  contact: '/contact',
  pricing: '/pricing',
  auth: {
    login: '/auth/login',
  },
  dashboard: {
    inicio: '/dashboard',  
    oficina: {
      personal: '/oficina/personal',
      roles: '/oficina/roles',
      ingresos: '/oficina/ingresos',
      costos: '/oficina/costos',
      materiales: '/oficina/inventario/materiales',
      movimientos: '/oficina/inventario/movimientos',
      pendientes: '/oficina/pendientes',
    },
    proyectos: {
      index: '/proyectos',
      crear: '/proyectos/crear',
      detalle: (id: string) => `/proyectos/${id}`,
      presupuestos: (id: string) => `/proyectos/${id}/presupuestos`,
      fechas: (id: string) => `/proyectos/${id}/fechas`,
      pagos: (id: string) => `/proyectos/${id}/pagos`,
      ingresos: (id: string) => `/proyectos/${id}/ingresos`,
      asignaciones: (id: string) => `/proyectos/${id}/asignaciones`,
      revisiones: (id: string) => `/proyectos/${id}/revisiones`,
      inventario: (id: string) => `/proyectos/${id}/inventario`,
    },
    maquinaria: {
      index: '/maquinaria',
      crear: '/maquinaria/crear',
      detalle: (id: string) => `/maquinaria/${id}`,
      asignaciones: (id: string) => `/maquinaria/${id}/asignaciones`,
      gastos: (id: string) => `/maquinaria/${id}/gastos`,
      estado: (id: string) => `/maquinaria/${id}/estado`,
    },
  },
  components: {
    index: '/components',
    dataDisplay: {
      detailLists: '/components/data-display/detail-lists',
      tables: '/components/data-display/tables',
      quickStats: '/components/data-display/quick-stats',
    },
    lists: {
      groupedLists: '/components/lists/grouped-lists',
      gridLists: '/components/lists/grid-lists',
    },
    forms: '/components/forms',
    modals: '/components/modals',
    charts: '/components/charts',
    buttons: '/components/buttons',
    typography: '/components/typography',
    colors: '/components/colors',
    inputs: '/components/inputs',
  },
  docs: 'https://material-kit-pro-react-docs.devias.io',
  notAuthorized: '/401',
  notFound: '/404',
  serverError: '/500',
};
